export const noteConstants = {

    GET_ALL_NOTE_REQUEST : 'GET_ALL_NOTE_REQUEST ',
    GET_ALL_NOTE_SUCCESS: 'GET_ALL_NOTE_SUCCESS ',
    GET_ALL_NOTE_FAILURE : 'GET_ALL_NOTE_FAILURE ',

    ADD_NOTE_REQUEST : 'ADD_NOTE_REQUEST ',
    ADD_NOTE_SUCCESS: 'ADD_NOTE_SUCCESS ',
    ADD_NOTE_FAILURE : 'ADD_NOTE_FAILURE ',

  

     GET_NOTES_BY_USER_REQUEST : 'GET_NOTES_BY_USER_REQUEST',
 GET_NOTES_BY_USER_SUCCESS : 'GET_NOTES_BY_USER_SUCCESS',
 GET_NOTES_BY_USER_FAILURE : 'GET_NOTES_BY_USER_FAILURE',

 GET_NOTE_REQUEST: 'GET_NOTE_REQUEST',      
 GET_NOTE_SUCCESS: 'GET_NOTE_SUCCESS',      
 GET_NOTE_FAILURE: 'GET_NOTE_FAILURE', 
 
 // Pour mettre à jour une note
 EDIT_NOTE_REQUEST : 'EDIT_NOTE_REQUEST ',
 EDIT_NOTE_SUCCESS: 'EDIT_NOTE_SUCCESS ',
 EDIT_NOTE_FAILURE : 'EDIT_NOTE_FAILURE ',
 
 // Pour supprimer une note
 DELETE_NOTE_REQUEST : 'DELETE_NOTE_REQUEST ',
 DELETE_NOTE_SUCCESS: 'DELETE_NOTE_SUCCESS ',
 DELETE_NOTE_FAILURE : 'DELETE_NOTE_FAILURE ',
} 
// export const coursConstants = {
//     GET_ALL_COURS_REQUEST: 'GET_ALL_COURS_REQUEST',
//     GET_ALL_COURS_SUCCESS: 'GET_ALL_COURS_SUCCESS',
//     GET_ALL_COURS_FAILURE: 'GET_ALL_COURS_FAILURE',

//     ADD_COURS_REQUEST: 'ADD_COURS_REQUEST',
//     ADD_COURS_SUCCESS: 'ADD_COURS_SUCCESS',
//     ADD_COURS_FAILURE: 'ADD_COURS_FAILURE',

//     GET_COURS_REQUEST: 'GET_COURS_REQUEST',
//     GET_COURS_SUCCESS: 'GET_COURS_SUCCESS',
//     GET_COURS_FAILURE: 'GET_COURS_FAILURE',

//     GET_COURS_BY_USER_REQUEST: 'GET_COURS_BY_USER_REQUEST',
//     GET_COURS_BY_USER_SUCCESS: 'GET_COURS_BY_USER_SUCCESS',
//     GET_COURS_BY_USER_FAILURE: 'GET_COURS_BY_USER_FAILURE',

//     EDIT_COURS_REQUEST: 'EDIT_COURS_REQUEST',
//     EDIT_COURS_SUCCESS: 'EDIT_COURS_SUCCESS',
//     EDIT_COURS_FAILURE: 'EDIT_COURS_FAILURE',

//     DELETE_COURS_REQUEST: 'DELETE_COURS_REQUEST',
//     DELETE_COURS_SUCCESS: 'DELETE_COURS_SUCCESS',
//     DELETE_COURS_FAILURE: 'DELETE_COURS_FAILURE',
// };
export const coursConstants = {
    GET_ALL_COURS_REQUEST: 'GET_ALL_COURS_REQUEST',
    GET_ALL_COURS_SUCCESS: 'GET_ALL_COURS_SUCCESS',
    GET_ALL_COURS_FAILURE: 'GET_ALL_COURS_FAILURE',
    ADD_COURS_REQUEST: 'ADD_COURS_REQUEST',
    ADD_COURS_SUCCESS: 'ADD_COURS_SUCCESS',
    ADD_COURS_FAILURE: 'ADD_COURS_FAILURE',
    GET_COURS_BY_USER_REQUEST: 'GET_COURS_BY_USER_REQUEST',
    GET_COURS_BY_USER_SUCCESS: 'GET_COURS_BY_USER_SUCCESS',
    GET_COURS_BY_USER_FAILURE: 'GET_COURS_BY_USER_FAILURE',
    GET_COURS_BY_ID_REQUEST: 'GET_COURS_BY_ID_REQUEST',
    GET_COURS_BY_ID_SUCCESS: 'GET_COURS_BY_ID_SUCCESS',
    GET_COURS_BY_ID_FAILURE: 'GET_COURS_BY_ID_FAILURE',
    EDIT_COURS_REQUEST: 'EDIT_COURS_REQUEST',
    EDIT_COURS_SUCCESS: 'EDIT_COURS_SUCCESS',
    EDIT_COURS_FAILURE: 'EDIT_COURS_FAILURE',
    DELETE_COURS_REQUEST: 'DELETE_COURS_REQUEST',
    DELETE_COURS_SUCCESS: 'DELETE_COURS_SUCCESS',
    DELETE_COURS_FAILURE: 'DELETE_COURS_FAILURE',
    GET_SIGNED_URL_REQUEST: 'GET_SIGNED_URL_REQUEST',
    GET_SIGNED_URL_SUCCESS: 'GET_SIGNED_URL_SUCCESS',
    GET_SIGNED_URL_FAILURE: 'GET_SIGNED_URL_FAILURE',
  };
export const formulaireStageConstants = {

    GET_ALL_FORMULAIRE_STAGE_REQUEST : 'GET_ALL_FORMULAIRE_STAGE_REQUEST ',
    GET_ALL_FORMULAIRE_STAGE_SUCCESS: 'GET_ALL_FORMULAIRE_STAGE_SUCCESS ',
    GET_ALL_FORMULAIRE_STAGE_FAILURE : 'GET_ALL_FORMULAIRE_STAGE_FAILURE ',



    ADD_FORMULAIRE_STAGE_REQUEST : 'ADD_FORMULAIRE_STAGE_REQUEST ',
    ADD_FORMULAIRE_STAGE_SUCCESS: 'ADD_FORMULAIRE_STAGE_SUCCESS ',
    ADD_FORMULAIRE_STAGE_FAILURE : 'ADD_FORMULAIRE_STAGE_FAILURE ',


    DELETE_FORMULAIRE_STAGE_REQUEST : 'DELETE_FORMULAIRE_STAGE_REQUEST ',
    DELETE_FORMULAIRE_STAGE_SUCCESS: 'DELETE_FORMULAIRE_STAGE_SUCCESS ',
    DELETE_FORMULAIRE_STAGE_FAILURE : 'DELETE_FORMULAIRE_STAGE_FAILURE ',

    EDIT_FORMULAIRE_STAGE_REQUEST : 'EDIT_FORMULAIRE_STAGE_REQUEST ',
    EDIT_FORMULAIRE_STAGE_SUCCESS: 'EDIT_FORMULAIRE_STAGE_SUCCESS ',
    EDIT_FORMULAIRE_STAGE_FAILURE : 'EDIT_FORMULAIRE_STAGE_FAILURE ',
} 
export const attestationConstants = {

    GET_ALL_ATTESTATION_REQUEST : 'GET_ALL_ATTESTATION_REQUEST ',
    GET_ALL_ATTESTATION_SUCCESS: 'GET_ALL_ATTESTATION_SUCCESS ',
    GET_ALL_ATTESTATION_FAILURE : 'GET_ALL_ATTESTATION_FAILURE ',

    ADD_ATTESTATION_REQUEST : 'ADD_ATTESTATION_REQUEST ',
    ADD_ATTESTATION_SUCCESS: 'ADD_ATTESTATION_SUCCESS ',
    ADD_ATTESTATION_FAILURE : 'ADD_ATTESTATION_FAILURE ',

  

     GET_ATTESTATIONS_BY_USER_REQUEST : 'GET_ATTESTATIONS_BY_USER_REQUEST',
 GET_ATTESTATIONS_BY_USER_SUCCESS : 'GET_ATTESTATIONS_BY_USER_SUCCESS',
 GET_ATTESTATIONS_BY_USER_FAILURE : 'GET_ATTESTATIONS_BY_USER_FAILURE',

 GET_ATTESTATION_REQUEST: 'GET_ATTESTATION_REQUEST',      
 GET_ATTESTATION_SUCCESS: 'GET_ATTESTATION_SUCCESS',      
 GET_ATTESTATION_FAILURE: 'GET_ATTESTATION_FAILURE', 
 
 // Pour mettre à jour une note
 EDIT_ATTESTATION_REQUEST : 'EDIT_ATTESTATION_REQUEST ',
 EDIT_ATTESTATION_SUCCESS: 'EDIT_ATTESTATION_SUCCESS ',
 EDIT_ATTESTATION_FAILURE : 'EDIT_ATTESTATION_FAILURE ',
 
 // Pour supprimer une note
 DELETE_ATTESTATION_REQUEST : 'DELETE_ATTESTATION_REQUEST ',
 DELETE_ATTESTATION_SUCCESS: 'DELETE_ATTESTATION_SUCCESS ',
 DELETE_ATTESTATION_FAILURE : 'DELETE_ATTESTATION_FAILURE ',

 UPDATE_ATTESTATION_STATUS_REQUEST : 'UPDATE_ATTESTATION_STATUS_REQUEST',
 UPDATE_ATTESTATION_STATUS_SUCCESS : 'UPDATE_ATTESTATION_STATUS_SUCCESS',
 UPDATE_ATTESTATION_STATUS_FAILURE : 'UPDATE_ATTESTATION_STATUS_FAILURE',
} 


export const reclamationConstants = {

    GET_ALL_RECLAMATION_REQUEST : 'GET_ALL_RECLAMATION_REQUEST ',
    GET_ALL_RECLAMATION_SUCCESS: 'GET_ALL_RECLAMATION_SUCCESS ',
    GET_ALL_RECLAMATION_FAILURE : 'GET_ALL_RECLAMATION_FAILURE ',

    ADD_RECLAMATION_REQUEST : 'ADD_RECLAMATION_REQUEST ',
    ADD_RECLAMATION_SUCCESS: 'ADD_RECLAMATION_SUCCESS ',
    ADD_RECLAMATION_FAILURE : 'ADD_RECLAMATION_FAILURE ',

  

     GET_RECLAMATIONS_BY_USER_REQUEST : 'GET_RECLAMATIONS_BY_USER_REQUEST',
 GET_RECLAMATIONS_BY_USER_SUCCESS : 'GET_RECLAMATIONS_BY_USER_SUCCESS',
 GET_RECLAMATIONS_BY_USER_FAILURE : 'GET_RECLAMATIONS_BY_USER_FAILURE',

 GET_RECLAMATION_REQUEST: 'GET_RECLAMATION_REQUEST',      
 GET_RECLAMATION_SUCCESS: 'GET_RECLAMATION_SUCCESS',      
 GET_RECLAMATION_FAILURE: 'GET_RECLAMATION_FAILURE', 
 
 // Pour mettre à jour une note
 EDIT_RECLAMATION_REQUEST : 'EDIT_RECLAMATION_REQUEST ',
 EDIT_RECLAMATION_SUCCESS: 'EDIT_RECLAMATION_SUCCESS ',
 EDIT_RECLAMATION_FAILURE : 'EDIT_RECLAMATION_FAILURE ',
 
 // Pour supprimer une note
 DELETE_RECLAMATION_REQUEST : 'DELETE_RECLAMATION_REQUEST ',
 DELETE_RECLAMATION_SUCCESS: 'DELETE_RECLAMATION_SUCCESS ',
 DELETE_RECLAMATION_FAILURE : 'DELETE_RECLAMATION_FAILURE ',

 UPDATE_RECLAMATION_RESPONSE_REQUEST  : 'UPDATE_RECLAMATION_RESPONSE_REQUEST',
 UPDATE_RECLAMATION_RESPONSE_SUCCESS : 'UPDATE_RECLAMATION_RESPONSE_SUCCESS',
 UPDATE_RECLAMATION_RESPONSE_FAILURE : 'UPDATE_RECLAMATION_RESPONSE_FAILURE',
} 

export const notificationConstants = {

 FETCH_NOTIFICATIONS_REQUEST : 'FETCH_NOTIFICATIONS_REQUEST',
 FETCH_NOTIFICATIONS_SUCCESS : 'FETCH_NOTIFICATIONS_SUCCESS',
 FETCH_NOTIFICATIONS_FAILURE : 'FETCH_NOTIFICATIONS_FAILURE',

 FETCH_NOTIFICATION_REQUEST : 'FETCH_NOTIFICATION_REQUEST',
 FETCH_NOTIFICATION_SUCCESS : 'FETCH_NOTIFICATION_SUCCESS',
 FETCH_NOTIFICATION_FAILURE : 'FETCH_NOTIFICATION_FAILURE',

 UPDATE_NOTIFICATION_REQUEST : 'UPDATE_NOTIFICATION_REQUEST',
 UPDATE_NOTIFICATION_SUCCESS : 'UPDATE_NOTIFICATION_SUCCESS',
 UPDATE_NOTIFICATION_FAILURE : 'UPDATE_NOTIFICATION_FAILURE',
 
 CREATE_NOTIFICATION_REQUEST: 'CREATE_NOTIFICATION_REQUEST', // Ajoutez cette constante
 CREATE_NOTIFICATION_SUCCESS: 'CREATE_NOTIFICATION_SUCCESS', // Ajoutez cette constante
 CREATE_NOTIFICATION_FAILURE: 'CREATE_NOTIFICATION_FAILURE' ,

 DELETE_NOTIFICATION_REQUEST: 'DELETE_NOTIFICATION_REQUEST',
 DELETE_NOTIFICATION_SUCCESS: 'DELETE_NOTIFICATION_SUCCESS',
 DELETE_NOTIFICATION_FAILURE: 'DELETE_NOTIFICATION_FAILURE',

 GET_NOTIFICATION_COUNT_REQUEST: 'GET_NOTIFICATION_COUNT_REQUEST',
 GET_NOTIFICATION_COUNT_SUCCESS: 'GET_NOTIFICATION_COUNT_SUCCESS',
 GET_NOTIFICATION_COUNT_FAILURE: 'GET_NOTIFICATION_COUNT_FAILURE',

 RESET_NOTIFICATION_COUNT: 'RESET_NOTIFICATION_COUNT',

  
}
export const noteInfoConstants = {

    FETCH_NOTEINFOS_REQUEST : 'FETCH_NOTEINFOS_REQUEST',
    FETCH_NOTEINFOS_SUCCESS : 'FETCH_NOTEINFOS_SUCCESS',
    FETCH_NOTEINFOS_FAILURE : 'FETCH_NOTEINFOS_FAILURE',
   
    FETCH_NOTEINFO_REQUEST : 'FETCH_NOTEINFO_REQUEST',
    FETCH_NOTEINFO_SUCCESS : 'FETCH_NOTEINFO_SUCCESS',
    FETCH_NOTEINFO_FAILURE : 'FETCH_NOTEINFO_FAILURE',
   
    UPDATE_NOTEINFO_REQUEST : 'UPDATE_NOTEINFO_REQUEST',
    UPDATE_NOTEINFO_SUCCESS : 'UPDATE_NOTEINFO_SUCCESS',
    UPDATE_NOTEINFO_FAILURE : 'UPDATE_NOTEINFO_FAILURE',
    
    CREATE_NOTEINFO_REQUEST: 'CREATE_NOTEINFO_REQUEST', // Ajoutez cette constante
    CREATE_NOTEINFO_SUCCESS: 'CREATE_NOTEINFO_SUCCESS', // Ajoutez cette constante
    CREATE_NOTEINFO_FAILURE: 'CREATE_NOTEINFO_FAILURE' ,
   
    DELETE_NOTEINFO_REQUEST: 'DELETE_NOTEINFO_REQUEST',
    DELETE_NOTEINFO_SUCCESS: 'DELETE_NOTEINFO_SUCCESS',
    DELETE_NOTEINFO_FAILURE: 'DELETE_NOTEINFO_FAILURE',
   
    GET_NOTEINFO_COUNT_REQUEST: 'GET_NOTEINFO_COUNT_REQUEST',
    GET_NOTEINFO_COUNT_SUCCESS: 'GET_NOTEINFO_COUNT_SUCCESS',
    GET_NOTEINFO_COUNT_FAILURE: 'GET_NOTEINFO_COUNT_FAILURE',
   
    RESET_NOTEINFO_COUNT: 'RESET_NOTEINFO_COUNT',
   
     
   }
// src/constants/certifActionTypes.js
export const certifConstants ={ 


CREATE_CERTIF_REQUEST : 'CREATE_CERTIF_REQUEST',
CREATE_CERTIF_SUCCESS : 'CREATE_CERTIF_SUCCESS',
CREATE_CERTIF_FAILURE : 'CREATE_CERTIF_FAILURE',

GET_ALL_CERTIFS_REQUEST : 'GET_ALL_CERTIFS_REQUEST',
GET_ALL_CERTIFS_SUCCESS : 'GET_ALL_CERTIFS_SUCCESS',
GET_ALL_CERTIFS_FAILURE : 'GET_ALL_CERTIFS_FAILURE',

GET_CERTIF_REQUEST : 'GET_CERTIF_REQUEST',
GET_CERTIF_SUCCESS : 'GET_CERTIF_SUCCESS',
GET_CERTIF_FAILURE : 'GET_CERTIF_FAILURE',

UPDATE_CERTIF_REQUEST : 'UPDATE_CERTIF_REQUEST',
UPDATE_CERTIF_SUCCESS : 'UPDATE_CERTIF_SUCCESS',
UPDATE_CERTIF_FAILURE : 'UPDATE_CERTIF_FAILURE',

DELETE_CERTIF_REQUEST : 'DELETE_CERTIF_REQUEST',
DELETE_CERTIF_SUCCESS : 'DELETE_CERTIF_SUCCESS',
DELETE_CERTIF_FAILURE : 'DELETE_CERTIF_FAILURE',
}
export const annonceConstants ={ 


    CREATE_ANNONCE_REQUEST : 'CREATE_ANNONCE_REQUEST',
    CREATE_ANNONCE_SUCCESS : 'CREATE_ANNONCE_SUCCESS',
    CREATE_ANNONCE_FAILURE : 'CREATE_ANNONCE_FAILURE',
    
    GET_ALL_ANNONCES_REQUEST : 'GET_ALL_ANNONCES_REQUEST',
    GET_ALL_ANNONCES_SUCCESS : 'GET_ALL_ANNONCES_SUCCESS',
    GET_ALL_ANNONCES_FAILURE : 'GET_ALL_ANNONCES_FAILURE',
    
    GET_ANNONCE_REQUEST : 'GET_ANNONCE_REQUEST',
    GET_ANNONCE_SUCCESS : 'GET_ANNONCE_SUCCESS',
    GET_ANNONCE_FAILURE : 'GET_ANNONCE_FAILURE',
    
    UPDATE_ANNONCE_REQUEST : 'UPDATE_ANNONCE_REQUEST',
    UPDATE_ANNONCE_SUCCESS : 'UPDATE_ANNONCE_SUCCESS',
    UPDATE_ANNONCE_FAILURE : 'UPDATE_ANNONCE_FAILURE',
    
    DELETE_ANNONCE_REQUEST : 'DELETE_ANNONCE_REQUEST',
    DELETE_ANNONCE_SUCCESS : 'DELETE_ANNONCE_SUCCESS',
    DELETE_ANNONCE_FAILURE : 'DELETE_ANNONCE_FAILURE',
    }
export const eventConstants ={ 


    CREATE_EVENT_REQUEST : 'CREATE_EVENT_REQUEST',
    CREATE_EVENT_SUCCESS : 'CREATE_EVENT_SUCCESS',
    CREATE_EVENT_FAILURE : 'CREATE_EVENT_FAILURE',
    
    GET_ALL_EVENTS_REQUEST : 'GET_ALL_EVENTS_REQUEST',
    GET_ALL_EVENTS_SUCCESS : 'GET_ALL_EVENTS_SUCCESS',
    GET_ALL_EVENTS_FAILURE : 'GET_ALL_EVENTS_FAILURE',
    
    GET_EVENT_REQUEST : 'GET_EVENT_REQUEST',
    GET_EVENT_SUCCESS : 'GET_EVENT_SUCCESS',
    GET_EVENT_FAILURE : 'GET_EVENT_FAILURE',
    
    UPDATE_EVENT_REQUEST : 'UPDATE_EVENT_REQUEST',
    UPDATE_EVENT_SUCCESS : 'UPDATE_EVENT_SUCCESS',
    UPDATE_EVENT_FAILURE : 'UPDATE_EVENT_FAILURE',
    
    DELETE_EVENT_REQUEST : 'DELETE_EVENT_REQUEST',
    DELETE_EVENT_SUCCESS : 'DELETE_EVENT_SUCCESS',
    DELETE_EVENT_FAILURE : 'DELETE_EVENT_FAILURE',
    }

    export const priceConstants ={ 


        CREATE_PRICE_REQUEST : 'CREATE_PRICE_REQUEST',
        CREATE_PRICE_SUCCESS : 'CREATE_PRICE_SUCCESS',
        CREATE_PRICE_FAILURE : 'CREATE_PRICE_FAILURE',
        
        GET_ALL_PRICES_REQUEST : 'GET_ALL_PRICES_REQUEST',
        GET_ALL_PRICES_SUCCESS : 'GET_ALL_PRICES_SUCCESS',
        GET_ALL_PRICES_FAILURE : 'GET_ALL_PRICES_FAILURE',
        
        GET_PRICE_REQUEST : 'GET_PRICE_REQUEST',
        GET_PRICE_SUCCESS : 'GET_PRICE_SUCCESS',
        GET_PRICE_FAILURE : 'GET_PRICE_FAILURE',
        
        UPDATE_PRICE_REQUEST : 'UPDATE_PRICE_REQUEST',
        UPDATE_PRICE_SUCCESS : 'UPDATE_PRICE_SUCCESS',
        UPDATE_PRICE_FAILURE : 'UPDATE_PRICE_FAILURE',
        
        DELETE_PRICE_REQUEST : 'DELETE_PRICE_REQUEST',
        DELETE_PRICE_SUCCESS : 'DELETE_PRICE_SUCCESS',
        DELETE_PRICE_FAILURE : 'DELETE_PRICE_FAILURE',
        }

        export const rattrapageConstants = {

            GET_ALL_RATTRAPAGE_REQUEST : 'GET_ALL_RATTRAPAGE_REQUEST ',
            GET_ALL_RATTRAPAGE_SUCCESS: 'GET_ALL_RATTRAPAGE_SUCCESS ',
            GET_ALL_RATTRAPAGE_FAILURE : 'GET_ALL_RATTRAPAGE_FAILURE ',
        
            ADD_RATTRAPAGE_REQUEST : 'ADD_RATTRAPAGE_REQUEST ',
            ADD_RATTRAPAGE_SUCCESS: 'ADD_RATTRAPAGE_SUCCESS ',
            ADD_RATTRAPAGE_FAILURE : 'ADD_RATTRAPAGE_FAILURE ',
        
          
        
             GET_RATTRAPAGES_BY_USER_REQUEST : 'GET_RATTRAPAGES_BY_USER_REQUEST',
         GET_RATTRAPAGES_BY_USER_SUCCESS : 'GET_RATTRAPAGES_BY_USER_SUCCESS',
         GET_RATTRAPAGES_BY_USER_FAILURE : 'GET_RATTRAPAGES_BY_USER_FAILURE',
        
         GET_RATTRAPAGE_REQUEST: 'GET_RATTRAPAGE_REQUEST',      
         GET_RATTRAPAGE_SUCCESS: 'GET_RATTRAPAGE_SUCCESS',      
         GET_RATTRAPAGE_FAILURE: 'GET_RATTRAPAGE_FAILURE', 
         
         // Pour mettre à jour une note
         EDIT_RATTRAPAGE_REQUEST : 'EDIT_RATTRAPAGE_REQUEST ',
         EDIT_RATTRAPAGE_SUCCESS: 'EDIT_RATTRAPAGE_SUCCESS ',
         EDIT_RATTRAPAGE_FAILURE : 'EDIT_RATTRAPAGE_FAILURE ',
         
         // Pour supprimer une note
         DELETE_RATTRAPAGE_REQUEST : 'DELETE_RATTRAPAGE_REQUEST ',
         DELETE_RATTRAPAGE_SUCCESS: 'DELETE_RATTRAPAGE_SUCCESS ',
         DELETE_RATTRAPAGE_FAILURE : 'DELETE_RATTRAPAGE_FAILURE ',
        
         UPDATE_RATTRAPAGE_RESPONSE_REQUEST : 'UPDATE_RATTRAPAGE_STATUS_REQUEST',
         UPDATE_RATTRAPAGE_RESPONSE_SUCCESS : 'UPDATE_RATTRAPAGE_STATUS_SUCCESS',
         UPDATE_RATTRAPAGE_RESPONSE_FAILURE : 'UPDATE_RATTRAPAGE_STATUS_FAILURE',
        } 
        export const emploiConstants = {
            CREATE_EMPLOI_REQUEST: 'CREATE_EMPLOI_REQUEST',
            CREATE_EMPLOI_SUCCESS: 'CREATE_EMPLOI_SUCCESS',
            CREATE_EMPLOI_FAILURE: 'CREATE_EMPLOI_FAILURE',
        
            GET_ALL_EMPLOIS_REQUEST: 'GET_ALL_EMPLOIS_REQUEST',
            GET_ALL_EMPLOIS_SUCCESS: 'GET_ALL_EMPLOIS_SUCCESS',
            GET_ALL_EMPLOIS_FAILURE: 'GET_ALL_EMPLOIS_FAILURE',
        
            GET_EMPLOI_REQUEST: 'GET_EMPLOI_REQUEST',
            GET_EMPLOI_SUCCESS: 'GET_EMPLOI_SUCCESS',
            GET_EMPLOI_FAILURE: 'GET_EMPLOI_FAILURE',
        
            UPDATE_EMPLOI_REQUEST: 'UPDATE_EMPLOI_REQUEST',
            UPDATE_EMPLOI_SUCCESS: 'UPDATE_EMPLOI_SUCCESS',
            UPDATE_EMPLOI_FAILURE: 'UPDATE_EMPLOI_FAILURE',
        
            DELETE_EMPLOI_REQUEST: 'DELETE_EMPLOI_REQUEST',
            DELETE_EMPLOI_SUCCESS: 'DELETE_EMPLOI_SUCCESS',
            DELETE_EMPLOI_FAILURE: 'DELETE_EMPLOI_FAILURE',
        };

        export const classeConstants = {
            CREATE_CLASSE_REQUEST: 'CREATE_CLASSE_REQUEST',
            CREATE_CLASSE_SUCCESS: 'CREATE_CLASSE_SUCCESS',
            CREATE_CLASSE_FAILURE: 'CREATE_CLASSE_FAILURE',
        
            GET_ALL_CLASSES_REQUEST: 'GET_ALL_CLASSES_REQUEST',
            GET_ALL_CLASSES_SUCCESS: 'GET_ALL_CLASSES_SUCCESS',
            GET_ALL_CLASSES_FAILURE: 'GET_ALL_CLASSES_FAILURE',
        
            GET_CLASSE_REQUEST: 'GET_CLASSE_REQUEST',
            GET_CLASSE_SUCCESS: 'GET_CLASSE_SUCCESS',
            GET_CLASSE_FAILURE: 'GET_CLASSE_FAILURE',
        
            UPDATE_CLASSE_REQUEST: 'UPDATE_CLASSE_REQUEST',
            UPDATE_CLASSE_SUCCESS: 'UPDATE_CLASSE_SUCCESS',
            UPDATE_CLASSE_FAILURE: 'UPDATE_CLASSE_FAILURE',
        
            DELETE_CLASSE_REQUEST: 'DELETE_CLASSE_REQUEST',
            DELETE_CLASSE_SUCCESS: 'DELETE_CLASSE_SUCCESS',
            DELETE_CLASSE_FAILURE: 'DELETE_CLASSE_FAILURE',
        };
        

      export const testConstants= {

            TEST_CREATE_REQUEST : 'TEST_CREATE_REQUEST',
            TEST_CREATE_SUCCESS : 'TEST_CREATE_SUCCESS',
            TEST_CREATE_FAIL :'TEST_CREATE_FAIL',

            GET_ALL_TEST_REQUEST : 'GET_ALL_TEST_REQUEST ',
            GET_ALL_TEST_SUCCESS: 'GET_ALL_TEST_SUCCESS ',
            GET_ALL_TEST_FAILURE : 'GET_ALL_TEST_FAILURE ',


            GET_TEST_REQUEST: 'GET_TEST_REQUEST',      
            GET_TEST_SUCCESS: 'GET_TEST_SUCCESS',      
            GET_TEST_FAILURE: 'GET_TEST_FAILURE', 

            // Pour mettre à jour une note
            EDIT_TEST_REQUEST : 'EDIT_TEST_REQUEST ',
            EDIT_TEST_SUCCESS: 'EDIT_TEST_SUCCESS ',
            EDIT_TEST_FAILURE : 'EDIT_TEST_FAILURE ',

            // Pour supprimer une note
            DELETE_TEST_REQUEST : 'DELETE_TEST_REQUEST ',
            DELETE_TEST_SUCCESS: 'DELETE_TEST_SUCCESS ',
            DELETE_TEST_FAILURE : 'DELETE_TEST_FAILURE ',
}

export const projetConstants= {

    PROJET_CREATE_REQUEST : 'PROJET_CREATE_REQUEST',
    PROJET_CREATE_SUCCESS : 'PROJET_CREATE_SUCCESS',
    PROJET_CREATE_FAIL :'PROJET_CREATE_FAIL',

    GET_ALL_PROJET_REQUEST : 'GET_ALL_PROJET_REQUEST ',
    GET_ALL_PROJET_SUCCESS: 'GET_ALL_PROJET_SUCCESS ',
    GET_ALL_PROJET_FAILURE : 'GET_ALL_PROJET_FAILURE ',


    GET_PROJET_REQUEST: 'GET_PROJET_REQUEST',      
    GET_PROJET_SUCCESS: 'GET_PROJET_SUCCESS',      
    GET_PROJET_FAILURE: 'GET_PROJET_FAILURE', 

    // Pour mettre à jour une note
    EDIT_PROJET_REQUEST : 'EDIT_PROJET_REQUEST ',
    EDIT_PROJET_SUCCESS: 'EDIT_PROJET_SUCCESS ',
    EDIT_PROJET_FAILURE : 'EDIT_PROJET_FAILURE ',

    // Pour supprimer une note
    DELETE_PROJET_REQUEST : 'DELETE_PROJET_REQUEST ',
    DELETE_PROJET_SUCCESS: 'DELETE_PROJET_SUCCESS ',
    DELETE_PROJET_FAILURE : 'DELETE_PROJET_FAILURE ',
}
export const impressionProfConstants= {

    IMPRESSIONPROF_CREATE_REQUEST : 'IMPRESSIONPROF_CREATE_REQUEST',
    IMPRESSIONPROF_CREATE_SUCCESS : 'IMPRESSIONPROF_CREATE_SUCCESS',
    IMPRESSIONPROF_CREATE_FAIL :'IMPRESSIONPROF_CREATE_FAIL',

    GET_ALL_IMPRESSIONPROF_REQUEST : 'GET_ALL_IMPRESSIONPROF_REQUEST',
    GET_ALL_IMPRESSIONPROF_SUCCESS: 'GET_ALL_IMPRESSIONPROF_SUCCESS',
    GET_ALL_IMPRESSIONPROF_FAILURE : 'GET_ALL_IMPRESSIONPROF_FAILURE',

    GET_IMPRESSIONPROFS_BY_USER_REQUEST: 'GET_IMPRESSIONPROFS_BY_USER_REQUEST',
GET_IMPRESSIONPROFS_BY_USER_SUCCESS: 'GET_IMPRESSIONPROFS_BY_USER_SUCCESS',
GET_IMPRESSIONPROFS_BY_USER_FAILURE: 'GET_IMPRESSIONPROFS_BY_USER_FAILURE',

    GET_IMPRESSIONPROF_REQUEST: 'GET_IMPRESSIONPROF_REQUEST',      
    GET_IMPRESSIONPROF_SUCCESS: 'GET_IMPRESSIONPROF_SUCCESS',      
    GET_IMPRESSIONPROF_FAILURE: 'GET_IMPRESSIONPROF_FAILURE', 

    // Pour mettre à jour une note
    EDIT_IMPRESSIONPROF_REQUEST : 'EDIT_IMPRESSIONPROF_REQUEST',
    EDIT_IMPRESSIONPROF_SUCCESS: 'EDIT_IMPRESSIONPROF_SUCCESS',
    EDIT_IMPRESSIONPROF_FAILURE : 'EDIT_IMPRESSIONPROF_FAILURE',

    // Pour supprimer une note
    DELETE_IMPRESSIONPROF_REQUEST : 'DELETE_IMPRESSIONPROF_REQUEST',
    DELETE_IMPRESSIONPROF_SUCCESS: 'DELETE_IMPRESSIONPROF_SUCCESS',
    DELETE_IMPRESSIONPROF_FAILURE : 'DELETE_IMPRESSIONPROF_FAILURE',
}

export const materielProfConstants = {

    GET_ALL_MATERIELPROF_REQUEST : 'GET_ALL_MATERIELPROF_REQUEST ',
    GET_ALL_MATERIELPROF_SUCCESS: 'GET_ALL_MATERIELPROF_SUCCESS ',
    GET_ALL_MATERIELPROF_FAILURE : 'GET_ALL_MATERIELPROF_FAILURE ',

    ADD_MATERIELPROF_REQUEST : 'ADD_MATERIELPROF_REQUEST ',
    ADD_MATERIELPROF_SUCCESS: 'ADD_MATERIELPROF_SUCCESS ',
    ADD_MATERIELPROF_FAILURE : 'ADD_MATERIELPROF_FAILURE ',

  

     GET_MATERIELPROFS_BY_USER_REQUEST : 'GET_MATERIELPROFS_BY_USER_REQUEST',
 GET_MATERIELPROFS_BY_USER_SUCCESS : 'GET_MATERIELPROFS_BY_USER_SUCCESS',
 GET_MATERIELPROFS_BY_USER_FAILURE : 'GET_MATERIELPROFS_BY_USER_FAILURE',

 GET_MATERIELPROF_REQUEST: 'GET_MATERIELPROF_REQUEST',      
 GET_MATERIELPROF_SUCCESS: 'GET_MATERIELPROF_SUCCESS',      
 GET_MATERIELPROF_FAILURE: 'GET_MATERIELPROF_FAILURE', 

 GET_ALL_MATERIELPROFS_REQUEST: 'GET_ALL_MATERIELPROFS_REQUEST',      
 GET_ALL_MATERIELPROFS_SUCCESS: 'GET_ALL_MATERIELPROFS_SUCCESS',      
 GET_ALL_MATERIELPROFS_FAILURE: 'GET_ALL_MATERIELPROFS_FAILURE', 
 
 // Pour mettre à jour une note
 EDIT_MATERIELPROF_REQUEST : 'EDIT_MATERIELPROF_REQUEST ',
 EDIT_MATERIELPROF_SUCCESS: 'EDIT_MATERIELPROF_SUCCESS ',
 EDIT_MATERIELPROF_FAILURE : 'EDIT_MATERIELPROF_FAILURE ',
 
 // Pour supprimer une note
 DELETE_MATERIELPROF_REQUEST : 'DELETE_MATERIELPROF_REQUEST ',
 DELETE_MATERIELPROF_SUCCESS: 'DELETE_MATERIELPROF_SUCCESS ',
 DELETE_MATERIELPROF_FAILURE : 'DELETE_MATERIELPROF_FAILURE ',

 UPDATE_MATERIELPROF_STATUS_REQUEST : 'UPDATE_MATERIELPROF_STATUS_REQUEST',
 UPDATE_MATERIELPROF_STATUS_SUCCESS : 'UPDATE_MATERIELPROF_STATUS_SUCCESS',
 UPDATE_MATERIELPROF_STATUS_FAILURE : 'UPDATE_MATERIELPROF_STATUS_FAILURE',
} 


export const contactProfConstants = {

    GET_ALL_CONTACTPROF_REQUEST : 'GET_ALL_CONTACTPROF_REQUEST ',
    GET_ALL_CONTACTPROF_SUCCESS: 'GET_ALL_CONTACTPROF_SUCCESS ',
    GET_ALL_CONTACTPROF_FAILURE : 'GET_ALL_CONTACTPROF_FAILURE ',

    ADD_CONTACTPROF_REQUEST : 'ADD_CONTACTPROF_REQUEST ',
    ADD_CONTACTPROF_SUCCESS: 'ADD_CONTACTPROF_SUCCESS ',
    ADD_CONTACTPROF_FAILURE : 'ADD_CONTACTPROF_FAILURE ',

  

     GET_CONTACTPROFS_BY_USER_REQUEST : 'GET_CONTACTPROFS_BY_USER_REQUEST',
 GET_CONTACTPROFS_BY_USER_SUCCESS : 'GET_CONTACTPROFS_BY_USER_SUCCESS',
 GET_CONTACTPROFS_BY_USER_FAILURE : 'GET_CONTACTPROFS_BY_USER_FAILURE',

 GET_CONTACTPROF_REQUEST: 'GET_CONTACTPROF_REQUEST',      
 GET_CONTACTPROF_SUCCESS: 'GET_CONTACTPROF_SUCCESS',      
 GET_CONTACTPROF_FAILURE: 'GET_CONTACTPROF_FAILURE', 
 
 // Pour mettre à jour une note
 EDIT_CONTACTPROF_REQUEST : 'EDIT_CONTACTPROF_REQUEST ',
 EDIT_CONTACTPROF_SUCCESS: 'EDIT_CONTACTPROF_SUCCESS ',
 EDIT_CONTACTPROF_FAILURE : 'EDIT_CONTACTPROF_FAILURE ',
 
 // Pour supprimer une note
 DELETE_CONTACTPROF_REQUEST : 'DELETE_CONTACTPROF_REQUEST ',
 DELETE_CONTACTPROF_SUCCESS: 'DELETE_CONTACTPROF_SUCCESS ',
 DELETE_CONTACTPROF_FAILURE : 'DELETE_CONTACTPROF_FAILURE ',

 UPDATE_CONTACTPROF_STATUS_REQUEST : 'UPDATE_CONTACTPROF_STATUS_REQUEST',
 UPDATE_CONTACTPROF_STATUS_SUCCESS : 'UPDATE_CONTACTPROF_STATUS_SUCCESS',
 UPDATE_CONTACTPROF_STATUS_FAILURE : 'UPDATE_CONTACTPROF_STATUS_FAILURE',
} 

export const commentaireConstants = {
    GET_ALL_COMMENTAIRE_REQUEST: 'GET_ALL_COMMENTAIRE_REQUEST',
    GET_ALL_COMMENTAIRE_BY_COUR_REQUEST: 'GET_ALL_COMMENTAIRE_BY_COUR_REQUEST',
    GET_ALL_COMMENTAIRE_SUCCESS: 'GET_ALL_COMMENTAIRE_SUCCESS',
    GET_ALL_COMMENTAIRE_FAILURE: 'GET_ALL_COMMENTAIRE_FAILURE',
    ADD_COMMENTAIRE_REQUEST: 'ADD_COMMENTAIRE_REQUEST',
    ADD_COMMENTAIRE_SUCCESS: 'ADD_COMMENTAIRE_SUCCESS',
    ADD_COMMENTAIRE_FAILURE: 'ADD_COMMENTAIRE_FAILURE',
    GET_COMMENTAIRE_BY_USER_REQUEST: 'GET_COMMENTAIRE_BY_USER_REQUEST',
    GET_COMMENTAIRE_BY_USER_SUCCESS: 'GET_COMMENTAIRE_BY_USER_SUCCESS',
    GET_COMMENTAIRE_BY_USER_FAILURE: 'GET_COMMENTAIRE_BY_USER_FAILURE',
    GET_COMMENTAIRE_BY_ID_REQUEST: 'GET_COMMENTAIRE_BY_ID_REQUEST',
    GET_COMMENTAIRE_BY_ID_SUCCESS: 'GET_COMMENTAIRE_BY_ID_SUCCESS',
    GET_COMMENTAIRE_BY_ID_FAILURE: 'GET_COMMENTAIRE_BY_ID_FAILURE',
    EDIT_COMMENTAIRE_REQUEST: 'EDIT_COMMENTAIRE_REQUEST',
    EDIT_COMMENTAIRE_SUCCESS: 'EDIT_COMMENTAIRE_SUCCESS',
    EDIT_COMMENTAIRE_FAILURE: 'EDIT_COMMENTAIRE_FAILURE',
    DELETE_COMMENTAIRE_REQUEST: 'DELETE_COMMENTAIRE_REQUEST',
    DELETE_COMMENTAIRE_SUCCESS: 'DELETE_COMMENTAIRE_SUCCESS',
    DELETE_COMMENTAIRE_FAILURE: 'DELETE_COMMENTAIRE_FAILURE',
    GET_SIGNED_URL_REQUEST: 'GET_SIGNED_URL_REQUEST',
    GET_SIGNED_URL_SUCCESS: 'GET_SIGNED_URL_SUCCESS',
    GET_SIGNED_URL_FAILURE: 'GET_SIGNED_URL_FAILURE',
  };

//   export const messageConstants = {
//     GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
//     GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
//     GET_MESSAGES_FAILURE: 'GET_MESSAGES_FAILURE',
//     SEND_MESSAGE_REQUEST: 'SEND_MESSAGE_REQUEST',
//     SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
//     SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',
//     CLEAR_MESSAGE: 'CLEAR_MESSAGE',
// };

// export const messageConstants = {
//     GET_ALL_MESSAGE_REQUEST: 'GET_ALL_MESSAGE_REQUEST',
//     // GET_ALL_MESSAGE_BY_COUR_REQUEST: 'GET_ALL_MESSAGE_BY_COUR_REQUEST',
//     GET_ALL_MESSAGE_SUCCESS: 'GET_ALL_MESSAGE_SUCCESS',
//     GET_ALL_MESSAGE_FAILURE: 'GET_ALL_MESSAGE_FAILURE',
//     ADD_MESSAGE_REQUEST: 'ADD_MESSAGE_REQUEST',
//     ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE_SUCCESS',
//     ADD_MESSAGE_FAILURE: 'ADD_MESSAGE_FAILURE',
//     GET_MESSAGE_BY_USER_REQUEST: 'GET_MESSAGE_BY_USER_REQUEST',
//     GET_MESSAGE_BY_USER_SUCCESS: 'GET_MESSAGE_BY_USER_SUCCESS',
//     GET_MESSAGE_BY_USER_FAILURE: 'GET_MESSAGE_BY_USER_FAILURE',
//     GET_MESSAGE_BY_ID_REQUEST: 'GET_MESSAGE_BY_ID_REQUEST',
//     GET_MESSAGE_BY_ID_SUCCESS: 'GET_MESSAGE_BY_ID_SUCCESS',
//     GET_MESSAGE_BY_ID_FAILURE: 'GET_MESSAGE_BY_ID_FAILURE',
//     EDIT_MESSAGE_REQUEST: 'EDIT_MESSAGE_REQUEST',
//     EDIT_MESSAGE_SUCCESS: 'EDIT_MESSAGE_SUCCESS',
//     EDIT_MESSAGE_FAILURE: 'EDIT_MESSAGE_FAILURE',
//     DELETE_MESSAGE_REQUEST: 'DELETE_MESSAGE_REQUEST',
//     DELETE_MESSAGE_SUCCESS: 'DELETE_MESSAGE_SUCCESS',
//     DELETE_MESSAGE_FAILURE: 'DELETE_MESSAGE_FAILURE',
//     GET_SIGNED_URL_REQUEST: 'GET_SIGNED_URL_REQUEST',
//     GET_SIGNED_URL_SUCCESS: 'GET_SIGNED_URL_SUCCESS',
//     GET_SIGNED_URL_FAILURE: 'GET_SIGNED_URL_FAILURE',
//   };

export const messageConstants = {
    GET_ALL_MESSAGE_REQUEST: 'GET_ALL_MESSAGE_REQUEST',
    GET_ALL_MESSAGE_SUCCESS: 'GET_ALL_MESSAGE_SUCCESS',
    GET_ALL_MESSAGE_FAILURE: 'GET_ALL_MESSAGE_FAILURE',
    ADD_MESSAGE_REQUEST: 'ADD_MESSAGE_REQUEST',
    ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE_SUCCESS',
    ADD_MESSAGE_FAILURE: 'ADD_MESSAGE_FAILURE',
  };
  export const userConstants = {
    GET_ETUDIANTS_REQUEST: 'GET_ETUDIANTS_REQUEST',
    GET_ETUDIANTS_SUCCESS: 'GET_ETUDIANTS_SUCCESS',
    GET_ETUDIANTS_FAILURE: 'GET_ETUDIANTS_FAILURE',
    // autres constantes...
  };
  export const USER_CONSTANTS = {
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
    // Autres constantes liées aux utilisateurs
  };