export const onLine = [
    {
      cover: "./images/courses/online/calendrierJ.png",
      hoverCover: "./images/courses/online/calendrierW.png",
      courseName: "PLANNING",
      course: "GET IT",
    },
    {
      cover: "./images/courses/online/offreJ.png",
      hoverCover: "./images/courses/online/offreW.png",
      courseName: "OFFRE",
      course: "Gérer",
    },
    {
      cover: "./images/courses/online/profJ.png",
      hoverCover: "./images/courses/online/profW.png",
      courseName: "TRAINER",
      course: "PUSH ONE",
    },
    {
      cover: "./images/courses/online/etudiantJ.png",
      hoverCover: "./images/courses/online/etudiantW.png",
      courseName: "STUDENT",
      course: "Gérer",
    },
    {
      cover: "./images/courses/online/classeJ.png",
      hoverCover: "./images/courses/online/classeW.png",
      courseName: "CLASSE",
      course: "30 Courses",
    },
    {
      cover: "./images/courses/online/scolmatiereJ.png",
      hoverCover: "./images/courses/online/scolmatiereW.png",
      courseName: "MATIERE",
      course: "Start",
    },
    {
      cover: "./images/courses/online/scolabsenceJ.png",
      hoverCover: "./images/courses/online/scolabsenceW.png",
      courseName: "ABSENCE",
      course: "Gérer",
    },
    {
      cover: "./images/courses/online/scolrattrapageJ.png",
      hoverCover: "./images/courses/online/scolrattrapageW.png",
      courseName: "RATTRAPAGE",
      course: "Gérer",
    },
    {
      cover: "./images/courses/online/scolecouteJ.png",
      hoverCover: "./images/courses/online/scolecouteW.png",
      courseName: "SUPPORT",
      course: "Ecouter",
    },
    {
      cover: "./images/courses/online/scolcontactJ.png",
      hoverCover: "./images/courses/online/scolcontactW.png",
      courseName: "MESSAGERIE",
      course: "Consulter",
    },
    {
      cover: "./images/courses/online/scolcertifJ.png",
      hoverCover: "./images/courses/online/scolcertifW.png",
      courseName: "CERTIFS",
      course: "Consulter ",
    },
    {
      cover: "./images/courses/online/scoleventJ.png",
      hoverCover: "./images/courses/online/scoleventW.png",
      courseName: "LOISIRS",
      course: "Consulter ",
    },
    {
      cover: "./images/courses/online/annonceJ.png",
      hoverCover: "./images/courses/online/annonceW.png",
      courseName: "ANNONCES",
      course: "Consulter ",
    },
    {
      cover: "./images/courses/online/scolprojetJ.png",
      hoverCover: "./images/courses/online/projetwhite.png",
      courseName: "PROJETS",
      course: "Consulter ",
    },
    {
      cover: "./images/courses/online/scolstageJ.png",
      hoverCover: "./images/courses/online/scolstageW.png",
      courseName: "STAGES",
      course: "Consulter ",
    },
    {
      cover: "./images/courses/online/pricingJ.png",
      hoverCover: "./images/courses/online/pricingW.png",
      courseName: "PRICING",
      course: "Consulter ",
    },
    {
      cover: "./images/courses/online/scolmaterielJ.png",
      hoverCover: "./images/courses/online/scolmaterielW.png",
      courseName: "MATERIEL",
      course: "Consulter ",
    },
    {
      cover: "./images/courses/online/scolimpressionJ.png",
      hoverCover: "./images/courses/online/scolimpressionW.png",
      courseName: "IMPRESSION",
      course: "Consulter ",
    },
  ]